// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  characterActive: string
  characterBase: string
  clipContainer: string
  fullClip: string
  halfClip: string
  hovered: string
  interactive: string
  itemWrapper: string
  notHovered: string
  rateContainer: string
  readonly: string
}
declare const cssExports: CssExports
export default cssExports
