// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  border: string
  't-table': string
  't-table__tbody': string
  't-table__td': string
  't-table__th': string
  't-table__thead': string
  't-table__tr': string
  't-table__wrapper': string
  tTable: string
  tTableTbody: string
  tTableTd: string
  tTableTh: string
  tTableThead: string
  tTableTr: string
  tTableWrapper: string
}
declare const cssExports: CssExports
export default cssExports
