name: Publish new versions on npm
run-name: ${{github.actor}}
on:
  release:
    types: [published] # 监听 github Release 发布
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-versions: '22.11.0'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install pnpm
        run: npm i -g pnpm@10.6.5
      - name: Install dependencies
        run: pnpm install
      - name: Extract version from release tag
        run: |
          # 从 GitHub Release 标签提取版本号，移除前缀 'v'（如果有）
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"
      - name: Build components
        run: ./shell/build.sh $PACKAGE_VERSION
      - name: Create Git Repository
        run: |
          cd ./dist/@trove-ui
          # 创建一个新的 Git 仓库
          git init
          git config user.name "zijian-feng"
          git config user.email "fengzijian@happcloudsign.com"
      - name: Publish new versions on npm
        run: |
          cd ./dist/@trove-ui
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
